import{a as S,S as q,i as n}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const P="56077039-3a5cc0c41ca2a13984a31b614",B="https://pixabay.com/api/";async function y(i,t=1){const{data:r}=await S.get(B,{params:{key:P,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return r}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function m(i){const t=i.map(({webformatURL:r,largeImageURL:c,tags:e,likes:o,views:a,comments:v,downloads:w})=>`
        <a href="${c}">
          <img src="${r}" alt="${e}" loading="lazy" />
          <div class="info">
            <p><b>Likes</b> ${o}</p>
            <p><b>Views</b> ${a}</p>
            <p><b>Comments</b> ${v}</p>
            <p><b>Downloads</b> ${w}</p>
          </div>
        </a>
      `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){f.innerHTML=""}function g(){p.classList.add("visible")}function b(){p.classList.remove("visible")}function L(){h.style.visibility="visible"}function l(){h.style.visibility="hidden"}const R=document.querySelector(".form"),O=document.querySelector(".load-more");let u="",s=1,d=0;R.addEventListener("submit",async i=>{i.preventDefault();const t=i.target["search-text"].value.trim();if(t){u=t,s=1,M(),l(),g();try{const r=await y(u,s);if(d=r.totalHits,r.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(r.hits),s*15<d?L():(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{b()}}});O.addEventListener("click",async()=>{s+=1,l(),g();try{const i=await y(u,s);m(i.hits);const t=document.querySelector(".gallery a");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}s*15<d?L():(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
