import{a as v,S as w,i as l}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="56077039-3a5cc0c41ca2a13984a31b614",q="https://pixabay.com/api/";async function f(a,t=1){const{data:o}=await v.get(q,{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return o}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(a){const t=a.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:c,comments:b,downloads:L})=>`
    <a href="${i}">
      <img src="${o}" alt="${e}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b> ${r}</p>
        <p><b>Views</b> ${c}</p>
        <p><b>Comments</b> ${b}</p>
        <p><b>Downloads</b> ${L}</p>
      </div>
    </a>
  `).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){h.innerHTML=""}function g(){p.classList.add("visible")}function m(){p.classList.remove("visible")}const $=document.querySelector(".form"),n=document.querySelector(".load-more");let d="",s=1,u=0;$.addEventListener("submit",async a=>{a.preventDefault();const t=a.target["search-text"].value.trim();if(t){d=t,s=1,R(),n.hidden=!0,g();try{const o=await f(d,s);if(u=o.totalHits,o.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits),s*15<u?n.hidden=!1:(n.hidden=!0,l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{m()}}});n.addEventListener("click",async()=>{s+=1,n.hidden=!0,g();try{const a=await f(d,s);y(a.hits);const t=document.querySelector(".gallery a");if(t){const{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}s*15<u?n.hidden=!1:(n.hidden=!0,l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
