import{a as L,S as w,i as c}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(e){if(e.ep)return;e.ep=!0;const i=o(e);fetch(e.href,i)}})();const S="56077039-3a5cc0c41ca2a13984a31b614",q="https://pixabay.com/api/";async function y(r,t=1){const{data:o}=await L.get(q,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return o}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:o,largeImageURL:s,tags:e,likes:i,views:l,comments:b,downloads:v})=>`
    <a href="${s}">
      <img src="${o}" alt="${e}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b> ${i}</p>
        <p><b>Views</b> ${l}</p>
        <p><b>Comments</b> ${b}</p>
        <p><b>Downloads</b> ${v}</p>
      </div>
    </a>
  `).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){f.innerHTML=""}function g(){p.classList.add("visible")}function m(){p.classList.remove("visible")}const $=document.querySelector(".form"),a=document.querySelector(".load-more");let d="",n=1,u=0;$.addEventListener("submit",async r=>{r.preventDefault();const t=r.target["search-text"].value.trim();if(t){d=t,n=1,R(),a.style.visibility="hidden",g();try{const o=await y(d,n);if(u=o.totalHits,o.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(o.hits),n*15<u?a.style.visibility="visible":(a.style.visibility="hidden",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{m()}}});a.addEventListener("click",async()=>{n+=1,a.style.visibility="hidden",g();try{const r=await y(d,n);h(r.hits);const t=document.querySelector(".gallery a");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n*15<u?a.style.visibility="visible":(a.style.visibility="hidden",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
